"""empty message

Revision ID: 6dc11c45d2d4
Revises: 244d2cf9b32d
Create Date: 2022-12-02 02:14:00.735470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dc11c45d2d4'
down_revision = '244d2cf9b32d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thermometer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('test_user_table', 'name')
    op.drop_column('test_user_table', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_user_table', sa.Column('email', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('test_user_table', sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_table('thermometer')
    # ### end Alembic commands ###
