"""empty message

Revision ID: 244d2cf9b32d
Revises: 
Create Date: 2022-11-29 22:27:21.207660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244d2cf9b32d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_user_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_user_table')
    # ### end Alembic commands ###
