version: "3"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
        POSTGRES_USER: test
        POSTGRES_PASSWORD: test
        POSTGRES_DB: test
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./main/dbInit.d:/docker-entrypoint-initdb.d #初期データベース作成
    ports:
      - 5432:5432
    tty: true

  api:
    depends_on:
      - postgres
    container_name: "api"
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - ./main:/usr/src/server

volumes:
  db_data: