"""empty message

Revision ID: ea22e9a175a9
Revises: 4860f319cd41
Create Date: 2022-12-08 21:14:50.200077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea22e9a175a9'
down_revision = '4860f319cd41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('air_conditioner_setting', sa.Column('isActive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('air_conditioner_setting', 'isActive')
    # ### end Alembic commands ###
