"""empty message

Revision ID: 89b747c624ae
Revises: c09836f79008
Create Date: 2022-12-08 20:49:15.212616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b747c624ae'
down_revision = 'c09836f79008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('air_conditioner_setting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('mode', sa.Enum('cooling', 'heating', name='airconditionermodetype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('air_conditioner_setting')
    # ### end Alembic commands ###
