"""empty message

Revision ID: e3c1ee26956f
Revises: ea22e9a175a9
Create Date: 2022-12-09 01:01:14.768922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e3c1ee26956f'
down_revision = 'ea22e9a175a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('air_conditioner_setting', 'temperature',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('air_conditioner_setting', 'mode',
               existing_type=postgresql.ENUM('cooling', 'heating', name='airconditionermodetype'),
               nullable=False)
    op.alter_column('air_conditioner_setting', 'isActive',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('air_conditioner_setting', 'isActive',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('air_conditioner_setting', 'mode',
               existing_type=postgresql.ENUM('cooling', 'heating', name='airconditionermodetype'),
               nullable=True)
    op.alter_column('air_conditioner_setting', 'temperature',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
