"""empty message

Revision ID: 4860f319cd41
Revises: 89b747c624ae
Create Date: 2022-12-08 20:51:16.285927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4860f319cd41'
down_revision = '89b747c624ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'air_conditioner_setting', ['mode'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'air_conditioner_setting', type_='unique')
    # ### end Alembic commands ###
