"""empty message

Revision ID: 2964a8c6fe56
Revises: 204dcaa9d4f9
Create Date: 2022-12-09 13:18:25.344982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2964a8c6fe56'
down_revision = '204dcaa9d4f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('air_conditioner_setting', 'threshold',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('air_conditioner_setting', 'threshold',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
