"""empty message

Revision ID: 204dcaa9d4f9
Revises: e3c1ee26956f
Create Date: 2022-12-09 13:16:42.803033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '204dcaa9d4f9'
down_revision = 'e3c1ee26956f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('air_conditioner_setting', sa.Column('threshold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('air_conditioner_setting', 'threshold')
    # ### end Alembic commands ###
